alias ctags="`brew --prefix`/bin/ctags"
alias sg="shotgun -p 3000"

# Awesome terminal happy face
export PS1='$( [[ ${?#0} = "" ]] && echo ":) " || echo ":( " )'

# Unbreak broken, non-colored terminal
# export TERM='xterm-color'
alias sourcebashrc='source ~/.bashrc'
alias vibashrc='vi ~/.bashrc'
alias ls='ls -lahG'
alias j='cd ~/code'
alias df='cd ~/.wine/drive_c/Program\ Files/df_34_11_win && wine Dwarf\ Fortress.exe'
alias dt='cd ~/.wine/drive_c/Program\ Files/DwarfTherapist-0.6.12 && wine DwarfTherapist.exe'
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
export GREP_OPTIONS="--color"

# Erase duplicates in history
export HISTCONTROL=erasedups
# Store 10k history entries
export HISTSIZE=10000
# Append to the history file when exiting instead of overwriting it
shopt -s histappend

