
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

[[ -r ~/.bashrc ]] && . ~/.bashrc

# shims and autocomplete for rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
